matrix:
  include:
    - language: go
      go:
        - 1.9.2
      install:
      script:
        - make
    - language: node_js
      node_js:
        - "9"
      script:
        - make buildNodeFrontend