golang_url_shortener:
  image: mxschmitt/golang_url_shortener:latest@sha256:503d17ea6a8e86104127bb107ea921414ea64648f895bb28ef57048fa85a5731
  ports:
    - 8080:8080
  volumes:
    - ./data:/data
  environment:
    - GUS_BASE_URL=https://s.b0n.pl
    - GUS_GOOGLE_CLIENT_ID=
    - GUS_GOOGLE_CLIENT_SECRET=
    - GUS_GITHUB_CLIENT_ID=
    - GUS_GITHUB_CLIENT_SECRET=
    - GUS_MICROSOFT_CLIENT_ID=
    - GUS_MICROSOFT_CLIENT_SECRET=
  restart: always
